version: '2'
services:
  mysql:
    image: rothgar/rpi-mysql:5.5
    #build: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/backup:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      # Change for your existing database
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: blog
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: tT70oL&FI&HF2XH7Mx6T^z48

  wordpress:
    image: rothgar/rpi-wordpress:latest
    #build: wordpress
    volumes:
      - "./.data/wp:/srv/wordpress"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      VHOST: example.com
